dataset:
    camera:
        width: 3280 # in pixels
        height: 2464 # in pixels
        left:
            path_intrinsic: "camera_calibration/intrinsic_left.npy"
            path_distortion: "camera_calibration/distortion_left.npy"
        right:
            path_intrinsic: "camera_calibration/intrinsic_right.npy"
            path_distortion: "camera_calibration/distortion_right.npy"
        stereo:
            path_stereomap: "camera_calibration/stereo_map.xml"
            baseline: 30  # in cm
experiment:
    random_pose: True
    n_iterations: 200

poses:
    query:
        #position: [6600.        , 4763.        ,   61]
        position: [6600.        , 4750.        ,   61]
        orientation: [160, -40, 0]
    guess:
        position: [6600.        , 4755.        ,   70]
        orientation: [160, -40, 0]
    centroid:
        position: [6125., 4125., 34.]
    captured_transform:
        scaling: 100
        translation: [6675, 4630., 35]
        rotation: [90, -135, 0] # degrees

sampling:
    sd_guess_x: 10
    sd_guess_y: 10
    sd_guess_z: 10
    sd_guess_yaw: 5
    sd_guess_pitch: 5
    sd_guess_roll: 5
    number_samples: 10

results:
    folder: '10_10_10_45_45_45/'