dataset:
    type: 'ImagePairDataset'
    filename: data/test.hdf5
    single_image: False
    augmentation:
        photometric:
            enable: false
        homographic:
            enable: false