dataset:
    camera:
        width: 3280 # in pixels
        height: 2464 # in pixels
        left:
            path_intrinsic: "camera_calibration/intrinsic_left.npy"
            path_distortion: "camera_calibration/distortion_left.npy"
        right:
            path_intrinsic: "camera_calibration/intrinsic_right.npy"
            path_distortion: "camera_calibration/distortion_right.npy"
        stereo:
            path_stereomap: "camera_calibration/stereo_map.xml"
            baseline: 30  # in cm

poses:
    query:
        #position: [6600.        , 4763.        ,   61]
        position: [6600.        , 4750.        ,   61]
        orientation: [160, -40, 0]
    guess:
        position: [6600.        , 4755.        ,   61]
        orientation: [160, -40, 0]
    centroid:
        position: [6125., 4125., 34.]
    captured_transform:
        scaling: 100
        translation: [6675, 4630., 35]
        rotation: [90, -135, 0] # degrees


sampling:
    sd_query_pitch: 1
    sd_query_roll: 1
    sd_guess_x: 1
    sd_guess_y: 1
    sd_guess_z: 1
    sd_guess_yaw: 1
    sd_guess_pitch: 1
    sd_guess_roll: 1
    number_samples: 10